# 빌드된 JAR 실행용 OpenJDK 이미지
FROM openjdk:17-jdk-alpine

# 작업 디렉토리 설정
WORKDIR /app

# JAR 파일 복사
COPY app.jar app.jar

# 앱 실행
EXPOSE 8080
ENTRYPOINT ["java","-jar", "app.jar"]
#ENTRYPOINT ["java","-Xmx256m", "-Xms128m","-jar", "app.jar"]

HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
  CMD curl -f http://localhost:8080/actuator/health || exit 1

